name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: make test

    - name: Run race detector
      run: make race

    - name: Upload coverage
      run: |
        make coverage
        mkdir -p coverage
        mv coverage.out coverage/
      continue-on-error: true

    - name: Upload HTML report (optional)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: coverage/
